### ISSUE TITLE
transparency together with JPG output on default settings.

### ISSUE THREAD

**Issue by bennystarfighter** [AlmightyFloppyFish/imagene#1]
When using for an example **PNG** files as input with transparency and exporting them as **JPG** without any specific format settings the output file breaks since **JPG** doesn't support transparency.

Example: `<1.jpg append:2.png,right 3.jpg>` (**2.png** have transparent areas)

**Comment by simvux** [comment]
I am unable to reproduce, the issue is most likely some image viewers being confused when the format is PNG and the file extension is .jpg (since in this example imagene will default to PNG). I'll make a commit where the file output format gets selected based on the file extension you write in outfile. (and the format: action as an override switch)

**Comment by simvux** [comment]
Could you verify if bcbc69e5523e803c2c428a7d2cbf87785b1e4f90 fixes your issue? Since i was unable to reproduce to begin with.
